<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
function New-UDAntdTimeLineItem {
    param(
        [Parameter()]
        [string]$Id = (New-Guid).ToString(),
        [Parameter()]
        [string]$ClassName,
        [Parameter()]
        [string]$Color,
        [Parameter()]
        [scriptblock]$Content,
        [Parameter()]
        [PSTypeName("UniversalDashboard.Icon")]$Dot,
        [Parameter()]
        [ValidateSet("left","right")]
        [string]$Position,
        [Parameter()]
        [hashtable]$Style

    )

    End {

        if ($null -ne $OnClick) {
            if ($OnClick -is [scriptblock]) {
                $OnClick = New-UDEndpoint -Endpoint $OnClick -Id ($Id + "onClick")
            }
            elseif ($OnClick -isnot [UniversalDashboard.Models.Endpoint]) {
                throw "OnClick must be a script block or UDEndpoint"
            }
        }

        @{
            assetId = $AssetId 
            isPlugin = $true 
            type = "ud-antd-timeline-item"
            id = $Id
            className = $ClassName
            content = $Content.Invoke()
            color = $Color
            dot = $Dot
            position = $Position
            style = $Style
        }

    }
}
