<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
function New-UDAntdColumn {
    [CmdletBinding()]
    [OutputType("Ant.Design.Column")]
    param(
        [Parameter()]
        [string]$Id = (New-Guid).ToString(),
        [Parameter(mandatory)]
        [scriptblock]$Content,
        [Parameter()]
        [int]$Offset,
        [Parameter()]
        [int]$Span,
        [Parameter()]
        [int]$Pull,
        [Parameter()]
        [int]$Push,
        [Parameter()]
        [int]$Order,
        [Parameter()]
        [string]$Xs,
        [Parameter()]
        [string]$Sm,
        [Parameter()]
        [string]$Md,
        [Parameter()]
        [string]$Lg,
        [Parameter()]
        [string]$Xl,
        [Parameter()]
        [string]$Xxl,
        [Parameter()]
        [string]$Flex = "auto"
    )

    End {
        $AntdColumn = @{
            assetId  = $AssetId 
            isPlugin = $true 
            type     = "ud-antd-col"
            id       = $Id
            offset   = $Offset
            order    = $Order
            pull     = $Pull
            push     = $Push
            span     = $Span
            xs       = $Xs
            sm       = $Sm
            md       = $Md
            lg       = $Lg
            xl       = $Xl
            xxl      = $Xxl
            flex     = $Flex
            content  = $Content.Invoke()
        }
        $AntdColumn.PSTypeNames.Insert(0, "Ant.Design.Column")
        $AntdColumn
    }
}
