<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
function New-UDAntdRow {
    param(
        [Parameter()]
        [string]$Id = (New-Guid).ToString(),
        [Parameter()]
        [string]$ClassName,
        [Parameter()]
        [hashtable]$Style,
        [Parameter(mandatory)]
        [scriptblock]$Content,
        [Parameter()]
        [ValidateSet("top","middle","bottom")]
        [string]$Align,
        [Parameter()]
        [int]$Gutter,
        [Parameter()]
        [ValidateSet("start","end","center","space-around","space-between")]
        [string]$Justify,
        [Parameter()]
        [switch]$Flex
    )

    End {

        # if($IsEndpoint){
        #     $ValueFromEndpoint = New-UDEndpoint -Id $id -Endpoint $UserValue
        # }

        @{
            assetId = $AssetId 
            isPlugin = $true 
            type = "ud-antd-row"
            id = $Id
            className = $ClassName
            style = $Style
            content = $Content.Invoke()
            gutter = $Gutter
            align = $Align
            justify = $Justify
            flex = $Flex.IsPresent
            span = $Span

        }

    }
}
