<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
function New-UDAntdDescriptionListItem {
    [CmdletBinding(DefaultParameterSetName = 'Content')]
    param(
        [Parameter()]
        [string]$Id = (New-Guid).ToString(),
        [Parameter()]
        [string]$ClassName,
        [Parameter(ParameterSetName = 'Content')]
        [scriptblock]$Content,
        [Parameter()]
        [object]$Label,
        [Parameter(ParameterSetName = 'Text')]
        [string]$Text,
        [Parameter()]
        [string]$Span,
        [Parameter()]
        [switch]$IsEndpoint,
        [Parameter()]
        [switch]$AutoRefresh,
        [Parameter()]
        [int]$RefreshInterval = 5000,
        [Parameter()]
        [hashtable]$Style

    )

    End {

        if ($IsEndpoint.IsPresent) {
            if ($Content -is [scriptblock]) {
                $Endpoint = New-UDEndpoint -Endpoint $Content -Id $Id
            }
            elseif ($Content -isnot [UniversalDashboard.Models.Endpoint]) {
                throw "Content must be a script block or UDEndpoint"
            }
        }

        if($null -ne $Content){$ListContent = $Content.Invoke()}

        if($Label -is [scriptblock]){
            $ItemLabel = $Label.invoke()
        }else{
            $ItemLabel = $Label
        }

        @{
            assetId = $AssetId 
            isPlugin = $true 
            type = "ud-antd-descriptionlist-item"
            id = $Id
            className = $ClassName
            # isEndpoint = $IsEndpoint
            autoRefresh = $AutoRefresh.IsPresent
            refreshInterval = $RefreshInterval
            content = $ListContent
            text = $Text
            style = $Style
            label = $ItemLabel
            span = $Span
        }

    }
}
