<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
function New-UDAntdCard {
    param(
        [Parameter()]
        [string]$Id = (New-Guid).ToString(),
        [Parameter()]
        [string]$ClassName,
        [Parameter()]
        [object[]]$actions,
        [Parameter()]
        [object[]]$Extra,
        [Parameter()]
        [object]$Cover,
        [Parameter()]
        [switch]$Loading,
        [Parameter()]
        [switch]$Hoverable,
        [Parameter()]
        [switch]$Bordered,
        [Parameter()]
        [ValidateSet("small", "default")]
        [string]$Size,
        [Parameter()]
        [scriptblock]$Content,
        [Parameter()]
        [hashtable]$Style,
        [Parameter()]
        [hashtable]$HeadStyle,
        [Parameter()]
        [hashtable]$BodyStyle = @{ padding = '0px' },
        [Parameter()]
        [string]$Title,
        [Parameter()]
        [ValidateSet('inner')]
        [string]$Variant,
        [Parameter()]
        [switch]$IsEndpoint,
        [Parameter()]
        [switch]$AutoRefresh,
        [Parameter()]
        [int]$RefreshInterval = 5000
    )

    End {

        if ($null -ne $Content) {
            if ($IsEndpoint) {
                if ($Content -is [scriptblock]) {
                    $Endpoint = New-UDEndpoint -Endpoint $Content -Id $Id 
                    $CardContent = $Content.Invoke()
                    $BodyStyle.Clear()
                }
                elseif ($Content -isnot [UniversalDashboard.Models.Endpoint]) {
                    throw "Content must be a script block or UDEndpoint"
                }
            }
            else{
                $CardContent = $Content.Invoke()
            }
        }
        else {
            $CardContent = @()
        }
        


        # if($null -ne $actions){
        #     $cardActions = $actions.Invoke()
        # }

        @{
            assetId         = $AssetId 
            isPlugin        = $true 
            type            = "ud-antd-card"
            id              = $Id
            className       = $ClassName
            actions         = $Actions
            extra           = $Extra
            hoverable       = $Hoverable.IsPresent
            content         = $CardContent  
            bordered        = $Bordered.IsPresent
            cover           = $Cover
            size            = $Size
            title           = $Title
            style           = $Style
            headStyle       = $HeadStyle
            bodyStyle       = $BodyStyle
            variant         = $Variant
            isEndpoint      = $IsEndpoint.IsPresent
            autoRefresh     = $AutoRefresh.IsPresent
            refreshInterval = $RefreshInterval
        }

    }
}
