
<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
function New-UDAntdPopConfirm {
    [CmdletBinding(DefaultParameterSetName = "Default")]
    [OutputType("Ant.Design.PopConfirm")]
    param(
        [Parameter()]
        [string]$Id = (New-Guid).ToString(),
        [Parameter()]
        [object]$Icon,
        [Parameter()]
        [scriptblock]$OnConfirm,
        [Parameter()]
        [scriptblock]$OnCancel,
        [Parameter()]
        [string]$Title,
        [Parameter()]
        [string]$OkText = "OK",
        [Parameter()]
        [string]$CancelText = "Cancel",
        [Parameter()]
        [object]$Content,
        [Parameter()]
        [switch]$Disabled
    )

    End {

        if ($Null -ne $OnConfirm) {
            $OnConfirmEndpoint = New-UDEndpoint -Endpoint $OnConfirm -Id ( $Id + "onConfirm" )
        }

        if ($Null -ne $OnCancel) {
            $OnCancelEndpoint = New-UDEndpoint -Endpoint $OnCancel -Id ( $Id + "onCancel" )
        }

        $AntdPopConfirm = @{
            assetId    = $AssetId 
            isPlugin   = $true 
            type       = "ud-antd-popconfirm"
            id         = $Id
            title      = $Title
            content    = $Content
            okText     = $OkText
            cancelText = $CancelText
            icon       = $Icon
            
            disabled   = $Disabled.IsPresent
        }
        $AntdPopConfirm.PSTypeNames.Insert(0, 'Ant.Design.PopConfirm')
        $AntdPopConfirm
    }
}
