import { lazy } from "react"

export const AntdMenu = lazy(() => import(/* webpackChunkName: 'AntdMenu' */ "./menu/menu"))
export const AntdMenuItem = lazy(() => import(/* webpackChunkName: 'AntdMenuItem' */ "./menu-item/menu-item"))
export const AntdSubMenu = lazy(() => import(/* webpackChunkName: 'AntdSubMenu' */ "./menu-sub-menu/menu-sub-menu"))
export const AntdMenuItemGroup = lazy(() =>
	import(/* webpackChunkName: 'AntdMenuItemGroup' */ "./menu-item-group/menu-item-group")
)
export const AntdMenuDivider = lazy(() =>
	import(/* webpackChunkName: 'AntdMenuDivider' */ "./menu-divider/menu-divider")
)
export const AntdRow = lazy(() => import(/* webpackChunkName: 'AntdRow' */ "./Grid/row"))
export const AntdColumn = lazy(() => import(/* webpackChunkName: 'AntdColumn' */ "./Grid/column"))
export const AntdButton = lazy(() => import(/* webpackChunkName: 'AntdButton' */ "./button/button"))
export const AntdButtonGroup = lazy(() =>
	import(/* webpackChunkName: 'AntdButtonGroup' */ "./button-group/button-group")
)
export const AntdSwitch = lazy(() => import(/* webpackChunkName: 'AntdSwitch' */ "./switch/switch"))
export const AntdTimeLine = lazy(() => import(/* webpackChunkName: 'AntdTimeLine' */ "./timeline/timeline"))
export const AntdTimeLineItem = lazy(() => import(/* webpackChunkName: 'AntdTimeLineItem' */ "./timeline/timelineItem"))
export const AntdDrawer = lazy(() => import(/* webpackChunkName: 'AntdDrawer' */ "./drawer/drawer"))
export const AntdCard = lazy(() => import(/* webpackChunkName: 'AntdCard' */ "./card/card"))
export const AntdDescriptionList = lazy(() =>
	import(/* webpackChunkName: 'AntdDescriptionList' */ "./description/description")
)
export const AntdDescListItem = lazy(() =>
	import(/* webpackChunkName: 'AntdDescriptionListItem' */ "./description-item/description-item")
)
export const AntdBadge = lazy(() => import(/* webpackChunkName: 'AntdBadge' */ "./badge/antdBadge"))
export const AntdDropDown = lazy(() => import(/* webpackChunkName: 'AntdDropDown' */ "./dropdown/dropdown"))
export const AntdPopover = lazy(() => import(/* webpackChunkName: 'AntdPopover' */ "./popover/popover"))
export const AntdLayout = lazy(() => import(/* webpackChunkName: 'AntdLayout' */ "./Layout/Layout"))
export const AntdHeader = lazy(() => import(/* webpackChunkName: 'AntdHeader' */ "./Layout/Header"))
export const AntdContent = lazy(() => import(/* webpackChunkName: 'AntdContent' */ "./Layout/Content"))
export const AntdAutoComplete = lazy(() =>
	import(/* webpackChunkName: 'AntdAutoComplete' */ "./autocomplete/autocomplete")
)
export const AntdList = lazy(() => import(/* webpackChunkName: 'AntdHeader' */ "./list/list"))
export const AntdListItem = lazy(() => import(/* webpackChunkName: 'AntdHeader' */ "./listItem/listItem"))
export const AntdStatistic = lazy(() => import(/* webpackChunkName: 'AntdStatistic' */ "./statistic/statistic"))
export const AntdCarousel = lazy(() => import(/* webpackChunkName: 'AntdCarousel' */ "./carousel/carousel"))
export const AntdInput = lazy(() => import(/* webpackChunkName: 'AntdInput' */ "./input/input"))
export const AntdInputTextArea = lazy(() => import(/* webpackChunkName: 'AntdInputTextArea' */ "./input/textArea"))
export const AntdInputPassword = lazy(() => import(/* webpackChunkName: 'AntdInputPassword' */ "./input/password"))
export const AntdIcon = lazy(() => import(/* webpackChunkName: 'AntdIcon' */ "./icon/antdIcon"))
export const AntdRadio = lazy(() => import(/* webpackChunkName: 'AntdRadio' */ "./radio/radio"))
export const AntdRadioButton = lazy(() => import(/* webpackChunkName: 'AntdRadioButton' */ "./radio/radio-button"))
export const AntdRadioGroup = lazy(() => import(/* webpackChunkName: 'AntdRadioGroup' */ "./radio/radio-group"))
export const AntdCopyToClipboard = lazy(() =>
	import(/* webpackChunkName: 'AntdCopyToClipboard' */ "./copy-to-clipboard/copy-to-clipboard")
)
export const AntdAvatar = lazy(() => import(/* webpackChunkName: 'AntdAvatar' */ "./avatar/avatar"))
export const AntdSlider = lazy(() => import(/* webpackChunkName: 'AntdSlider' */ "./slider/slider"))
export const AntdNotification = lazy(() =>
	import(/* webpackChunkName: 'AntdNotification' */ "./notification/notification")
)
export const AntdMessage = lazy(() => import(/* webpackChunkName: 'AntdMessage' */ "./message/message"))
export const AntdSider = lazy(() => import(/* webpackChunkName: 'AntdSider' */ "./Layout/Sider"))
export const AntdComment = lazy(() => import(/* webpackChunkName: 'AntdComment' */ "./comment/comment"))
export const AntdSteps = lazy(() => import(/* webpackChunkName: 'AntdSteps' */ "./steps/steps"))
export const AntdStep = lazy(() => import(/* webpackChunkName: 'AntdStep' */ "./steps/step"))
export const AntdFooter = lazy(() => import(/* webpackChunkName: 'AntdFooter' */ "./footer/footer"))
export const AntdTable = lazy(() => import(/* webpackChunkName: 'AntdTable' */ "./table/table"))
export const AntdForm = lazy(() => import(/* webpackChunkName: 'AntdForm' */ "./form/antForm"))
export const AntdFormItem = lazy(() => import(/* webpackChunkName: 'AntdFormItem' */ "./form/antFormItem"))
export const AntdThemeButton = lazy(() => import(/* webpackChunkName: 'AntdThemeButton' */ "./theme/theme"))
export const AntdResultPage = lazy(() => import(/* webpackChunkName: 'AntdResultPage' */ "./framework/resultPage"))
export const AntdPageHeader = lazy(() => import(/* webpackChunkName: 'AntdPageHeader' */ "./framework/PageHeader"))
